#!/usr/bin/env node
'use strict';
const fs = require('fs');
const path = require('path');
const vm = require('vm');
const root = path.resolve(__dirname, '..');
const source = fs.readFileSync(path.join(root, 'src/ui/session-continuity.js'), 'utf8');
const values = new Map();
const primaryKey = 'ai-shorts-session-continuity-v112';
const backupKey = `${primaryKey}-backup-1`;
const protectedKey = `${primaryKey}-protected`;
values.set(primaryKey, JSON.stringify({ app: 'AI Shorts Studio', schemaVersion: 4, savedAt: '2026-07-23T01:00:00.000Z', fileName: 'latest.mp4', recommendations: [{ id: 'latest' }], selectedRecommendationId: 'latest', captions: [{ text: 'one' }], selectedRange: { start: 0, end: 15 }, settings: {}, copy: {} }));
values.set(backupKey, JSON.stringify({ app: 'AI Shorts Studio', schemaVersion: 4, savedAt: '2026-07-22T01:00:00.000Z', fileName: 'backup.mp4', recommendations: [{ id: 'backup' }], selectedRecommendationId: 'backup', captions: [], settings: {}, copy: {} }));
const localStorage = { get length() { return values.size; }, key(i) { return [...values.keys()][i] || null; }, getItem(key) { return values.has(key) ? values.get(key) : null; }, setItem(key, value) { values.set(key, String(value)); }, removeItem(key) { values.delete(key); } };
const state = { recommendations: [], selectedRecommendationId: '', settings: {}, captions: [] };
const document = { readyState: 'loading', hidden: false, body: { dataset: {} }, getElementById() { return null; }, querySelector() { return null; }, addEventListener() {}, dispatchEvent() {} };
const window = { window: null, document, localStorage, navigator: {}, CustomEvent: function CustomEvent() {}, AIShortsRuntimeConfig: { APP_VERSION: 'v1.5.26', SESSION_SCHEMA_VERSION: 4, SESSION_BACKUP_MIN_COUNT: 1, SESSION_BACKUP_COUNT: 2, SESSION_BACKUP_MAX_COUNT: 3 }, AIShortsProjectService: { CURRENT_SCHEMA_VERSION: 4, parseProjectText: JSON.parse, applyProjectSnapshot(current, snapshot) { Object.assign(current, { recommendations: snapshot.recommendations, selectedRecommendationId: snapshot.selectedRecommendationId, captions: snapshot.captions || [], settings: snapshot.settings || {} }); } }, AIShortsAppState: { state, addDiagnostic() {}, saveSettings() {} }, setTimeout, clearTimeout, setInterval() { return 1; }, clearInterval() {}, addEventListener() {} };
window.window = window;
vm.runInContext(source, vm.createContext({ window, document, localStorage, navigator: window.navigator, CustomEvent: window.CustomEvent, Object, String, Number, Math, Date, Set, Map, Promise, JSON, Blob, setTimeout, clearTimeout, console }), { filename: 'session-continuity.js' });
const api = window.AIShortsSessionContinuity;
if (!api.restoreSnapshot(backupKey)) throw new Error('backup selection must be restorable before protection');
const protectedResult = api.protectSelectedSnapshot();
if (!protectedResult.protected || !values.has(protectedKey)) throw new Error('selected recovery point must be copied into a non-rotating protected slot');
values.delete(backupKey);
const available = api.listAvailableSnapshots();
const protectedItem = available.find(item => item.kind === 'protected');
if (!protectedItem || !protectedItem.valid || protectedItem.fileName !== 'backup.mp4') throw new Error('protected backup must survive rotation-slot removal and remain independently restorable');
if (!api.restoreSnapshot(protectedKey) || state.selectedRecommendationId !== 'backup') throw new Error('protected backup must restore the protected project state');
const status = api.getStatus();
if (status.protectedBackupCount !== 1 || status.protectedBackup.key !== protectedKey) throw new Error('session status must expose the protected backup without raw project content');
if (!source.includes('sessionBackupPreview') || !source.includes('중요 백업 보호')) throw new Error('session UI must expose a selected-backup preview and protection control');
console.log('PASS protected non-rotating session backup and recovery preview contract');
