'use strict';
const fs=require('fs'),vm=require('vm'); const code=fs.readFileSync('src/diagnostics/support-diagnostics.js','utf8');
const window={AIShortsRuntimeConfig:{APP_VERSION:'v1.6.25'},Blob:global.Blob}; window.window=window;
vm.runInNewContext(code,{window,console,Date,Math,Object,Array,JSON,Promise});
const api=window.AIShortsSupportDiagnostics;
const normalized=api.normalizeBundle({appVersion:'v1.6.20',runtime:{webAudio:true,worker:true,serviceWorker:true,secureContext:true,runtimeErrors:0},analysis:{history:[]},benchmarks:[],serviceWorker:{controlled:true}});
const inspection={compatible:true,normalized};
const result=api.compareInspectionToCurrent(inspection,{runtimeHealth:{collect:()=>({webAudio:true,worker:true,serviceWorker:true,secureContext:true,runtimeErrors:2})},serviceWorkerRegistration:{controlled:false}});
if(!result.items.length||!result.items.every(x=>x.priority)) throw new Error('priority missing');
const ranks={critical:0,high:1,medium:2,low:3,none:4}; for(let i=1;i<result.items.length;i++) if(ranks[result.items[i-1].priority]>ranks[result.items[i].priority]) throw new Error('not sorted');
console.log('support diagnostics priority smoke passed');
